### ISSUE TITLE
Alloydb connector for C# .NET

### ISSUE THREAD

**Issue by tsingh2k15** [GoogleCloudPlatform/alloydb-python-connector#181]
### Question

Is there a roadmap for Alloydb connector for applications that are written in C# .NET? I know as an alternative, I can use auth-proxy.

**Comment by jackwotherspoon** [comment]
Hi @tsingh2k15 Thanks for the question 😄 

Currently an AlloyDB Connector for C# (.NET) is not in the roadmap for the near future. If there is enough interest then it may get added, so questions like this definitely help 👍 

As you mentioned you can use the AlloyDB Auth Proxy as an alternative. You may also find [this blog](https://esg.dev/posts/using-gcp-iam-with-pgsql/) interesting and worth a read, it explains how you can still leverage [automatic IAM authentication](https://cloud.google.com/sql/docs/postgres/iam-authentication) even without needing a Connector or Proxy. We will be adding a sample similar to it into our official docs soon. It was written for Cloud SQL but the same can be done for AlloyDB.

Thanks again for the question and your interest in AlloyDB Connectors.

**Comment by tsingh2k15** [comment]
> Hi @tsingh2k15 Thanks for the question 😄
> 
> Currently an AlloyDB Connector for C# (.NET) is not in the roadmap for the near future. If there is enough interest then it may get added, so questions like this definitely help 👍
> 
> As you mentioned you can use the AlloyDB Auth Proxy as an alternative. You may also find [this blog](https://esg.dev/posts/using-gcp-iam-with-pgsql/) interesting and worth a read, it explains how you can still leverage [automatic IAM authentication](https://cloud.google.com/alloydb/docs/manage-iam-authn) even without needing a Connector or Proxy for C#. We will be adding a sample similar to it into our official docs soon. It was written for Cloud SQL but the same can be done for AlloyDB.
> 
> Thanks again for the question and your interest in AlloyDB Connectors.

Thanks for the clarification, @jackwotherspoon. I have one follow up question which is related but different. In order to have efficient connection pooling and management, I was using pgBouncer in front of CloudSQL PostgreSQL. I understand the Alloydb is much more performant and uses a different architecture underneath. Is there any GCP documentation or reading which may be available on this topic as well? I am evaluating if I may have to use pgBouncer in front of Alloydb but at the same time I need to understand if I really need it. Any recommendation around this topic will help as well.
