### ISSUE TITLE
Support initializing an AsyncConnector outside of an async context

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-python-connector#203]
### Feature Description

Our current AsyncConnector must be initialized in an async context. To make it easier to use, we should support initializing the AsyncConnector outside of an async context.

This probably means trying to get the running loop, and creating one if that fails.

**Comment by RahulDubey391** [comment]
Hi @jackwotherspoon, if it's not a WIP, I can have a look into the issue. But need some guidance on how to approach.

**Comment by jackwotherspoon** [comment]
@RahulDubey391 I will be taking this one as we have a tight deadline and I already have the change started. Will let you know as we open future issues if there are some that you can tackle if you would like 😄

**Comment by RahulDubey391** [comment]
> @RahulDubey391 I will be taking this one as we have a tight deadline and I already have the change started. Will let you know as we open future issues if there are some that you can tackle if you would like 😄

Sure @jackwotherspoon, no issues! I am happy to help anytime ☺

**Comment by jackwotherspoon** [comment]
Closed by #207
