### ISSUE TITLE
Convert Connector Public IP and Automatic IAM AuthN tests into samples

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/alloydb-python-connector#222]
Add region tags around tests and convert tests into samples like direct path tests.

Depends on #220

**Comment by enocom** [comment]
The linked PR includes Auto IAM AuthN region tags too it seems.

**Comment by jackwotherspoon** [comment]
> The linked PR includes Auto IAM AuthN region tags too it seems.

Yes it does since this issue is for Public IP and Automatic IAM authn samples
