### ISSUE TITLE
Readme suggests enable_iam_auth with pg8000 should work

### ISSUE THREAD

**Issue by samsaam-thg** [GoogleCloudPlatform/alloydb-python-connector#293]
### Bug Description

With version 1.0.0, using iam auth with pg8000 does not work. After digging I read somewhere that pg8000 is currently unsupported. If that is the case, the README is misleading suggesting that it should work https://github.com/GoogleCloudPlatform/alloydb-python-connector?tab=readme-ov-file#automatic-iam-database-authentication , would have saved me some time to immediately be able to see pg8000 isn't supported.

### Example code (or command)

```Python
from google.cloud.alloydb.connector import Connector

conn = Connector().connect(f"projects/my-project/locations/europe-west2/clusters/my-cluster/instances/primary", "pg8000", user="me@gmail.com", db="postgres", enable_iam_auth=True, ip_type="public")
```

### Stacktrace

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/google/cloud/alloydb/connector/connector.py", line 123, in connect
    return connect_task.result()
  File "/Users/baigs/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/baigs/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/google/cloud/alloydb/connector/connector.py", line 190, in connect_async
    return await self._loop.run_in_executor(None, connect_partial)
  File "/Users/baigs/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/google/cloud/alloydb/connector/pg8000.py", line 43, in connect
    return pg8000.dbapi.connect(
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/pg8000/dbapi.py", line 211, in connect
    return Connection(
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/pg8000/dbapi.py", line 651, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/pg8000/core.py", line 383, in __init__
    self.message_types[code](_read(self._sock, data_len - 4), context)
  File "/Users/baigs/Library/Caches/pypoetry/virtualenvs/api-oRARjpf5-py3.10/lib/python3.10/site-packages/pg8000/core.py", line 594, in handle_AUTHENTICATION_REQUEST
    self.password.decode("utf8"),
AttributeError: 'NoneType' object has no attribute 'decode'
```

### Steps to reproduce?

Run example code

### Environment

1. OS type and version: MacOS Sonoma 14.4
2. Python version: 3.10.6
3. AlloyDB Python Connector version: 1.0.0

**Comment by jackwotherspoon** [comment]
@samsaam-thg you will also want to grant your IAM user the "Cloud AlloyDB Database User" role.

**Comment by samsaam-thg** [comment]
Jack, thanks for the quick response, you were right, I had a team member attempt after adding them as an IAM user (without the Cloud AlloyDB Database User role) and then I attempted with the Database User role without adding myself as an IAM user to the DB, silly mistake. I also can't find where I read that the async driver was supported and pg8000 was not supported yet, I may have hallucinated it.

Apologies :)

**Comment by samsaam-thg** [comment]
Follow up question, I'm using terraform to provision the IAM users, by default they [aren't granted any permissions](https://cloud.google.com/alloydb/docs/manage-iam-authn#grant-privileges) as I understand it, but it seems like via TF I could apply the `postgres` role and give IAMs access this way? Is this accurate? I'd like to avoid having to run some bootstrap scripts

**Comment by jackwotherspoon** [comment]
@samsaam-thg Glad you were able to get it to work! 😄 Had me scared there for a second, phew! 

 > I'm using terraform to provision the IAM users, by default they [aren't granted any permissions](https://cloud.google.com/alloydb/docs/manage-iam-authn#grant-privileges) as I understand it, but it seems like via TF I could apply the postgres role and give IAMs access this way? Is this accurate? I'd like to avoid having to run some bootstrap scripts

What you are running up against is currently a huge pain point that I too have run into on numerous occasions. I'm currently working with our Cloud SQL and AlloyDB API teams to look at creating a flag or argument to allow specifying roles to grant an IAM user upon creation of the database user. 

One thing I've had success with in the past is using the [`gcloud alloydb users set-superuser`](https://cloud.google.com/sdk/gcloud/reference/alloydb/users/set-superuser) command (I'm not sure if this command has made its way into terraform yet off the top of my head). This command allows you to grant an IAM user the superuser privileges which may suffice for your use-case.

Ideally down the road we will have support for specifying more granular permissions to give an IAM database user upon their creation. Hope this helps for now 😄

**Comment by samsaam-thg** [comment]
Yeah my bad :D 

Ah I see just to clarify, I seem to be able to do this with terraform:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_user#example-usage---alloydb-user-iam

```
resource "google_alloydb_user" "user2" {
  cluster = google_alloydb_cluster.default.name
  user_id = "user2@foo.com"
  user_type = "ALLOYDB_IAM_USER"

  database_roles = ["alloydbiamuser"]
  depends_on = [google_alloydb_instance.default]
}
```

Would setting database_roles = ["alloydbiamuser", "postgres"] not suffice?

**Comment by jackwotherspoon** [comment]
> Would setting database_roles = ["alloydbiamuser", "postgres"] not suffice?

It very well might work, but I have not attempted it that way myself. If you give it a try I'd love to know if it works or not 😄 Please let me know it does.

Another role to try and grant if it doesn't work would be `alloydbsuperuser` as that is what built-in database users are granted:
```
database_roles = ["alloydbiamuser", "alloydbsuperuser"]
```

**Comment by jackwotherspoon** [comment]
Awesome! Glad you were able to get a working solution. Thanks for updating the issue 😄 

I'll close this out now.
