### ISSUE TITLE
[How to] connect from Local Machine using Public IP

### ISSUE THREAD

**Issue by mahimairaja** [GoogleCloudPlatform/alloydb-python-connector#309]
Hi, i am facing an authentication issue while connection using the pg800 python connectors;

✅ Enabled Public IP for the instance

### Code: 

``` python
import pg8000
import sqlalchemy
from typing import Tuple

from google.cloud.alloydb.connector import Connector, IPTypes


def create_sqlalchemy_engine(
    inst_uri: str,
    user: str,
    password: str,
    db: str,
) -> Tuple[sqlalchemy.engine.Engine, Connector]:
    connector = Connector()

    def getconn() -> pg8000.dbapi.Connection:
        conn: pg8000.dbapi.Connection = connector.connect(
            inst_uri,
            "pg8000",
            user=user,
            password=password,
            db=db,
            # use ip_type to specify Public IP
            ip_type=IPTypes.PUBLIC,
        )
        return conn

    # create SQLAlchemy connection pool
    engine = sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator=getconn,
    )
    engine.dialect.description_encoding = None
    return engine, connector
```

### Error Message:

``` bash
---------------------------------------------------------------------------
TransportError                            Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py in refresh(self, request)
    127         try:
--> 128             self._retrieve_info(request)
    129             self.token, self.expiry = _metadata.get_service_account_token(

28 frames
TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7e16ec1a5180>)

The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py in refresh(self, request)
    132         except exceptions.TransportError as caught_exc:
    133             new_exc = exceptions.RefreshError(caught_exc)
--> 134             raise new_exc from caught_exc
    135 
    136     @property

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7e16ec1a5180>)
```

Please let me know, how to connect from local machine using the Public IP method.

**Comment by enocom** [comment]
Have you configured gcloud and run `gcloud auth application-default login`?

**Comment by jackwotherspoon** [comment]
@mahimairaja Like Eno mentioned  above this points at an auth issue probably from not setting ADC credentials properly which the Python Connector uses for authentication. You can read more about [setting ADC credentials here](https://cloud.google.com/docs/authentication/provide-credentials-adc).

Are you running your code on a GCE VM or local machine? It seems the auth library thinks you are running from a compute engine based on the error message.

**Comment by jackwotherspoon** [comment]
> From my understanding. setting ADC will automatically involves the initialization of IAM right?

Not sure I fully understand the sentence. For local deployment on your local machine (aka FastAPI development) you need to set  ADC credentials following the [steps for setting up ADC](https://cloud.google.com/docs/authentication/provide-credentials-adc). 

Either `gcloud auth application-default login` for setting IAM user credentials or you can set env variable `GOOGLE_APPLICATION_CREDENTIALS` to the path of a service account JSON file for an IAM service account.

In a deployed Google application environment (GCE, Cloud Run etc.) the ADC credentials are automatically set to the service account in the environment which is why you don't see this issue when deploying in other environments and only locally.

**Comment by jackwotherspoon** [comment]
@mahimairaja Yes you can just use the [google-github-actions/auth](https://github.com/google-github-actions/auth) Github Action. We recommend using the Github Action with [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines) for the best workflow.

Here is a [great blog showcasing the two together](https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions).

This is matter of fact the exact setup we use for our own integration tests in this repo:
https://github.com/GoogleCloudPlatform/alloydb-python-connector/blob/f2906196ef699ae056ba1ce1777b86cdbecf0a68/.github/workflows/tests.yaml#L155-L161

Hope this helps 😄 Going to close out this issue as the original question was answered and resolved.
